"""initial

Revision ID: 00ea585784fc
Revises: a707ccd3584b
Create Date: 2021-11-19 18:35:01.684700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00ea585784fc'
down_revision = 'a707ccd3584b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
