"""initial

Revision ID: 7900aed9ba11
Revises: f82dc6cfe4ed
Create Date: 2021-11-18 13:11:12.772426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7900aed9ba11'
down_revision = 'f82dc6cfe4ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserCreate', sa.Column('admin', sa.String(length=45), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserCreate', 'admin')
    # ### end Alembic commands ###
