"""initial

Revision ID: 9d0d685d5f51
Revises: 00ea585784fc
Create Date: 2021-11-19 18:37:52.509342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d0d685d5f51'
down_revision = '00ea585784fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Ticket_ibfk_2', 'Ticket', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('Ticket_ibfk_2', 'Ticket', 'UserCreate', ['idUser'], ['id'])
    # ### end Alembic commands ###
