"""initial

Revision ID: cd6a07cb2aa0
Revises: 0fcdb17e7416
Create Date: 2021-11-18 13:10:10.922280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd6a07cb2aa0'
down_revision = '0fcdb17e7416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
